"""add storage_key to documents, loosen file_url to nullable

Revision ID: 56a6e2322d1a
Revises: 11388e004306
Create Date: 2026-08-24 13:56:19.885340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a6e2322d1a'
down_revision: Union[str, None] = '11388e004306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.String(), nullable=True))
    op.alter_column('documents', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
