"""admin totp, signup attempts, org action codes

Revision ID: 50ac06aa4b9c
Revises: b8d2e4f60a17
Create Date: 2026-10-07 13:56:02.749499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ac06aa4b9c'
down_revision: Union[str, None] = 'b8d2e4f60a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signup_attempts_created_at'), 'signup_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_signup_attempts_ip'), 'signup_attempts', ['ip'], unique=False)
    op.create_table('org_action_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_action_codes_org_id'), 'org_action_codes', ['org_id'], unique=False)
    op.add_column('users', sa.Column('totp_secret_enc', sa.String(), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('totp_last_step', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('recovery_codes_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_codes_hash')
    op.drop_column('users', 'totp_last_step')
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret_enc')
    op.drop_index(op.f('ix_org_action_codes_org_id'), table_name='org_action_codes')
    op.drop_table('org_action_codes')
    op.drop_index(op.f('ix_signup_attempts_ip'), table_name='signup_attempts')
    op.drop_index(op.f('ix_signup_attempts_created_at'), table_name='signup_attempts')
    op.drop_table('signup_attempts')
    # ### end Alembic commands ###
