"""add custom field values, extend custom_fields with entity_type and metadata

Revision ID: 568685f84b73
Revises: 5ba8bc594079
Create Date: 2026-08-11 18:51:54.611218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568685f84b73'
down_revision: Union[str, None] = '5ba8bc594079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic — hand-adjusted below ###
    # custom_field_values is a brand-new table, no backfill concerns.
    op.create_table('custom_field_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('custom_field_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_field_id', 'entity_id', name='uq_custom_field_value_field_entity')
    )

    # custom_fields is an EXISTING table (models since Phase 1). Autogenerate
    # wanted to add entity_type as NOT NULL directly, which would fail on
    # any deployment that already has rows in it. In practice no real org
    # has ever been able to create a custom_fields row — the feature never
    # had a UI or route to write through until this phase — but we don't
    # trust that assumption blindly (see MANUAL.md's "add all_2" Phase 4/5
    # lessons on schema-vs-data drift). Add nullable, backfill defensively,
    # THEN tighten to NOT NULL, so this migration is safe even if that
    # assumption turns out to be wrong on some environment we don't know
    # about.
    op.add_column('custom_fields', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('custom_fields', sa.Column('options', sa.String(), nullable=True))
    op.add_column('custom_fields', sa.Column('is_required', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('custom_fields', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('custom_fields', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('custom_fields', sa.Column('created_at', sa.DateTime(), nullable=True))

    op.execute("UPDATE custom_fields SET entity_type = module WHERE entity_type IS NULL")
    op.alter_column('custom_fields', 'entity_type', nullable=False)

    op.create_unique_constraint('uq_custom_field_org_entity_name', 'custom_fields', ['org_id', 'entity_type', 'field_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # custom_field_values must go first — it holds a FK to custom_fields.
    op.drop_table('custom_field_values')
    op.drop_constraint('uq_custom_field_org_entity_name', 'custom_fields', type_='unique')
    op.drop_column('custom_fields', 'created_at')
    op.drop_column('custom_fields', 'display_order')
    op.drop_column('custom_fields', 'is_active')
    op.drop_column('custom_fields', 'is_required')
    op.drop_column('custom_fields', 'options')
    op.drop_column('custom_fields', 'entity_type')
    # ### end Alembic commands ###
