"""add invite-by-email fields to users

Revision ID: 11388e004306
Revises: d61c9a1f7ecc
Create Date: 2026-08-24 04:45:20.280034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11388e004306'
down_revision: Union[str, None] = 'd61c9a1f7ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('invite_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_invite_email_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_invite_email_sent_at')
    op.drop_column('users', 'invite_token_expires')
    op.drop_column('users', 'invite_token_hash')
    # ### end Alembic commands ###
