"""add email verification, password reset, and login rate limiting fields to users

Revision ID: 9f2fa35bb239
Revises: 568685f84b73
Create Date: 2026-08-13 15:59:57.517409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2fa35bb239'
down_revision: Union[str, None] = '568685f84b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - hand-corrected below ###
    # email_verified and failed_login_attempts are added as NOT NULL on
    # `users`, a table that has real rows in every org that already
    # exists (every test org this whole session, and any real deployed
    # org). Autogenerate's default (NOT NULL, no backfill) would fail
    # outright against a populated table - same category of bug already
    # caught and fixed twice before this phase (Phase 4's products.sku,
    # Phase 9's custom_fields.entity_type). Add nullable, backfill,
    # THEN tighten - the now-established correct shape for this project.
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))

    # Every existing user: hasn't verified under this new system (False,
    # not NULL/unknown), and has zero recorded failed attempts under this
    # new system (0, a real count, not a placeholder).
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    op.execute("UPDATE users SET failed_login_attempts = 0 WHERE failed_login_attempts IS NULL")

    op.alter_column('users', 'email_verified', nullable=False)
    op.alter_column('users', 'failed_login_attempts', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token_hash')
    op.drop_column('users', 'verification_token_expires')
    op.drop_column('users', 'verification_token_hash')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
