"""add last_verification_email_sent_at to users

Revision ID: d61c9a1f7ecc
Revises: 9f2fa35bb239
Create Date: 2026-08-15 17:34:18.336157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61c9a1f7ecc'
down_revision: Union[str, None] = '9f2fa35bb239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_verification_email_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_email_sent_at')
    # ### end Alembic commands ###
