"""add branding_storage_key to organizations

Revision ID: ee67f12de678
Revises: 56a6e2322d1a
Create Date: 2026-08-27 06:13:41.000545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee67f12de678'
down_revision: Union[str, None] = '56a6e2322d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('branding_storage_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'branding_storage_key')
    # ### end Alembic commands ###
